--INSERTS DA TABELA tb_usuarios Usuario
--tipo 1 ALUNOS
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2010-03-15', 1, 'usuario1@email.com', 'Usuario1');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2011-07-21', 1, 'usuario2@email.com', 'Usuario2');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2012-05-30', 1, 'usuario3@email.com', 'Usuario3');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2013-08-14', 1, 'usuario4@email.com', 'Usuario4');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2014-11-25', 1, 'usuario5@email.com', 'Usuario5');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2015-02-10', 1, 'usuario6@email.com', 'Usuario6');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2016-06-18', 1, 'usuario7@email.com', 'Usuario7');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2017-09-05', 1, 'usuario8@email.com', 'Usuario8');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2018-12-12', 1, 'usuario9@email.com', 'Usuario9');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2019-04-22', 1, 'usuario10@email.com', 'Usuario10');
--tipo 2 PROFESSORES
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2005-01-15', 2, 'usuario11@email.com', 'Usuario11');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2006-03-22', 2, 'usuario12@email.com', 'Usuario12');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2007-07-19', 2, 'usuario13@email.com', 'Usuario13');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2008-09-30', 2, 'usuario14@email.com', 'Usuario14');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2007-12-10', 2, 'usuario15@email.com', 'Usuario15');
--tipo 3 ADM
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2003-02-25', 3, 'usuario16@email.com', 'Usuario16');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2004-05-14', 3, 'usuario17@email.com', 'Usuario17');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2005-08-23', 3, 'usuario18@email.com', 'Usuario18');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2006-11-11', 3, 'usuario19@email.com', 'Usuario19');
INSERT INTO tb_usuarios (data_criacao, tipo, email, nome) VALUES ('2007-01-30', 3, 'usuario20@email.com', 'Usuario20');

--INSERTS DA TABELA tb_unidade_Matematica
INSERT INTO tb_unidade_Matematica (nome, descricao) VALUES ('Números','Desenvolver a noção de número, incluindo as ideias de aproximação, proporcionalidade, equivalência e ordem');
INSERT INTO tb_unidade_Matematica (nome, descricao) VALUES ('Álgebra','Desenvolver as ideias de equivalência, proporcionalidade, variação e interdependência');
INSERT INTO tb_unidade_Matematica (nome, descricao) VALUES ('Geometria','Estudar algoritmos e fluxogramas para resolver problemas geométricos');
INSERT INTO tb_unidade_Matematica (nome, descricao) VALUES ('Grandezas e medidas','Consolidar e ampliar a noção de número, aplicar noções geométricas e estruturar o pensamento algébrico');
INSERT INTO tb_unidade_Matematica (nome, descricao) VALUES ('Probabilidade e estatística','Resolver problemas envolvendo a comparação e equivalência de valores monetários, identificar resultados possíveis, estimar probabilidades, ler e interpretar dados apresentados em tabelas e gráficos');

--=======TB_HABILIDADES======== *Bimestre conforme curriculo paulista
--INSERTS DO ANO 6
--Habilidades NÚMEROS do 6º ano: MA01 - MA18
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA01', 'Comparar, ordenar, ler e escrever números naturais e números racionais cuja representação decimal é finita, fazendo uso da reta numérica.','Sistema de numeração decimal: características, leitura, escrita e comparação de números naturais e de números racionais representados na forma decimal', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA02', 'Reconhecer o sistema de numeração decimal, como o que prevaleceu no mundo ocidental, e destacar semelhanças e diferenças com outros sistemas, de modo a sistematizar suas principais características (base, valor posicional e função do zero), utilizando, inclusive, a composição e decomposição de números naturais e números racionais em sua representação decimal.','Sistema de numeração decimal: características, leitura, escrita e comparação de números naturais e de números racionais representados na forma decimal', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA03', 'Resolver e elaborar problemas que envolvam cálculos (mentais ou escritos, exatos ou aproximados) com números naturais, por meio de estratégias variadas, com compreensão dos processos neles envolvidos com e sem uso de calculadora.','Operações (adição, subtração, multiplicação, divisão e potenciação) com números naturais. Divisão euclidiana', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA04', 'Construir algoritmo em linguagem natural e representá-lo por fluxograma que indique a resolução de um problema simples (por exemplo, se um número natural qualquer é par).', 'Fluxograma para determinar a paridade de um número natural. Múltiplos e divisores de um número natural.  Números primos e compostos', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA05', 'Classificar números naturais em primos e compostos, estabelecer relações entre números, expressas pelos termos “é múltiplo de”, “é divisor de”, “é fator de”, e estabelecer, por meio de investigações, critérios de divisibilidade por 2, 3, 4, 5, 6, 8, 9, 10, 100 e 1000.', 'Fluxograma para determinar a paridade de um número natural. Múltiplos e divisores de um número natural.  Números primos e compostos', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA06', 'Resolver e elaborar problemas que envolvam as ideias de múltiplo e de divisor.', 'Fluxograma para determinar a paridade de um número natural. Múltiplos e divisores de um número natural.  Números primos e compostos', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA07', 'Compreender, comparar e ordenar frações associadas às ideias de partes de inteiros e resultado de divisão, identificando frações equivalentes.', 'Frações: significados (parte/todo, quociente), equivalência, comparação, adição e subtração; cálculo da fração de um número natural; adição e subtração de frações', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA08', 'Reconhecer que os números racionais positivos podem ser expressos nas formas fracionária e decimal, estabelecer relações entre essas representações, passando de uma representação para outra, e relacionálos a pontos na reta numérica.', 'Frações: significados (parte/todo, quociente), equivalência, comparação, adição e subtração; cálculo da fração de um número natural; adição e subtração de frações', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA09', 'Resolver e elaborar problemas que envolvam o cálculo da fração de uma quantidade e cujo resultado seja um número natural, com e sem uso de calculadora.', 'Frações: significados (parte/todo, quociente), equivalência, comparação, adição e subtração; cálculo da fração de um número natural; adição e subtração de frações', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA10', 'Resolver e elaborar problemas que envolvam adição ou subtração com números racionais positivos na representação fracionária.', 'Frações: significados (parte/todo, quociente), equivalência, comparação, adição e subtração; cálculo da fração de um número natural; adição e subtração de frações', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA11', 'Resolver e elaborar problemas com números racionais positivos na representação decimal, envolvendo as quatro operações fundamentais e a potenciação, por meio de estratégias diversas, utilizando estimativas e arredondamentos para verificar a razoabilidade de respostas, com e sem uso de calculadora.', 'Operações (adição, subtração, multiplicação, divisão e potenciação) com números racionais', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA12', 'Fazer estimativas de quantidades e aproximar números para múltiplos da potência de 10 mais próxima.', 'Aproximação de números para múltiplos de potências de 10', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 6, 'EF06MA13', 'Resolver e elaborar problemas que envolvam porcentagens, com base na ideia de proporcionalidade, sem fazer uso da “regra de três”, utilizando estratégias pessoais, cálculo mental e calculadora, em contextos de educação financeira, entre outros.', 'Cálculo de porcentagens por meio de estratégias diversas, sem fazer uso da “regra de três”', 3);
--Habilidades ÁLGEBRA do 6º ano: MA14 - MA15
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 6, 'EF06MA14', 'Reconhecer que a relação de igualdade matemática não se altera ao adicionar, subtrair, multiplicar ou dividir os seus dois membros por um mesmo número e utilizar essa noção para determinar valores desconhecidos na resolução de problemas.', 'Propriedades da igualdade', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 6, 'EF06MA15', 'Resolver e elaborar problemas que envolvam a partilha de uma quantidade em duas partes desiguais, envolvendo relações aditivas e multiplicativas, bem como a razão entre as partes e entre uma das partes e o todo.', 'Problemas que tratam da partição de um todo em duas partes desiguais, envolvendo razões entre as partes e entre uma das partes e o todo', 4);
--Habilidades GEOMETRIA do 6º ano: MA16 - MA23
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA16', 'Associar pares ordenados de números a pontos do plano cartesiano do 1º quadrante, em situações como a localização dos vértices de um polígono.', 'Plano cartesiano: associação dos vértices de um polígono a pares ordenados', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA17', 'Quantificar e estabelecer relações entre o número de vértices, faces e arestas de prismas e pirâmides, em função do seu polígono da base, para resolver problemas e desenvolver a percepção espacial.', 'Prismas e pirâmides: planificações e relações entre seus elementos (vértices, faces e arestas)', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA18', 'Reconhecer, nomear e comparar polígonos, considerando lados, vértices e ângulos, e classificá-los em regulares e não regulares, tanto em suas representações no plano como em faces de poliedros.', 'Polígonos: classificações quanto ao número de vértices, às medidas de lados e ângulos e ao paralelismo e perpendicularismo dos lados', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA19', 'Identificar características dos triângulos e classificá-los em relação às medidas dos lados e dos ângulos.', 'Polígonos: classificações quanto ao número de vértices, às medidas de lados e ângulos e ao paralelismo e perpendicularismo dos lados', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA20', 'Identificar características dos quadriláteros, classificá-los em relação a lados e a ângulos e reconhecer a inclusão e a intersecção de classes entre eles.', 'Polígonos: classificações quanto ao número de vértices, às medidas de lados e ângulos e ao paralelismo e perpendicularismo dos lados', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA21', 'Construir figuras planas semelhantes em situações de ampliação e de redução, com o uso de malhas quadriculadas, plano cartesiano ou tecnologias digitais.', 'Construção de figuras semelhantes: ampliação e redução de figuras planas em malhas quadriculadas', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA22', 'Utilizar instrumentos, como réguas e esquadros, ou softwares para representações de retas paralelas e perpendiculares e construção de quadriláteros, entre outros.', 'Construção de retas paralelas e perpendiculares, fazendo uso de réguas, esquadros e softwares', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 6, 'EF06MA23', 'Construir algoritmo para resolver situações passo a passo (como na construção de dobraduras ou na indicação de deslocamento de um objeto no plano segundo pontos de referência e distâncias fornecidas etc.).', 'Construção de retas paralelas e perpendiculares, fazendo uso de réguas, esquadros e softwares', 0);
--Habilidades GRANDEZAS e MEDIDAS do 6º ano: MA24 - MA29
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA24', 'Resolver e elaborar problemas que envolvam as grandezas comprimento, massa, tempo, temperatura, área (triângulos e retângulos), capacidade e volume (sólidos formados por blocos retangulares), sem uso de fórmulas, inseridos, sempre que possível, em contextos oriundos de situações reais e/ou relacionadas às outras áreas do conhecimento.', 'Problemas sobre medidas envolvendo grandezas como comprimento, massa, tempo, temperatura, área, capacidade e volume', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA25', 'Reconhecer a abertura do ângulo como grandeza associada às figuras geométricas.', 'Ângulos: noção, usos e medida', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA26', 'Resolver problemas que envolvam a noção de ângulo em diferentes contextos e em situações reais, como ângulo de visão.', 'Ângulos: noção, usos e medida', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA27', 'Determinar medidas da abertura de ângulos, por meio de transferidor e/ou tecnologias digitais.', 'Ângulos: noção, usos e medida', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA28', 'Interpretar, descrever e desenhar plantas baixas simples de residências e vistas aéreas.', 'Plantas baixas e vistas aéreas', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 6, 'EF06MA29', 'Analisar e descrever mudanças que ocorrem no perímetro e na área de um quadrado ao se ampliarem ou reduzirem, igualmente, as medidas de seus lados, para compreender que o perímetro é proporcional à medida do lado, o que não ocorre com a área.', 'Perímetro de um quadrado como grandeza proporcional à medida do lado', 0);
--Habilidades PROBABILIDADE E ESTATÍSTICA do 6º ano: MA30 - MA34
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 6, 'EF06MA30', 'Calcular a probabilidade de um evento aleatório, expressando-a por número racional (forma fracionária, decimal e percentual) e comparar esse número com a probabilidade obtida por meio de experimentos sucessivos.', 'Cálculo de probabilidade como a razão entre o número de resultados favoráveis e o total de resultados possíveis em um espaço amostral equiprovável; Cálculo de probabilidade por meio de muitas repetições de um experimento (frequências de ocorrências e probabilidade frequentista)', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 6, 'EF06MA31', 'Identificar as variáveis e suas frequências e os elementos constitutivos (título, eixos, legendas, fontes e datas) em diferentes tipos de gráfico.', 'Leitura e interpretação de tabelas e gráficos (de colunas ou barras simples ou múltiplas) referentes a variáveis categóricas e variáveis numéricas', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 6, 'EF06MA32', 'Interpretar e resolver situações que envolvam dados de pesquisas sobre contextos ambientais, sustentabilidade, trânsito, consumo responsável, entre outros, apresentadas pela mídia em tabelas e em diferentes tipos de gráficos e redigir textos escritos com o objetivo de sintetizar conclusões.', 'Leitura e interpretação de tabelas e gráficos (de colunas ou barras simples ou múltiplas) referentes a variáveis categóricas e variáveis numéricas', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 6, 'EF06MA33', 'Planejar e coletar dados de pesquisa referente a práticas sociais escolhidas pelos alunos e fazer uso de planilhas eletrônicas para registro, representação e interpretação das informações, em tabelas, vários tipos de gráficos e texto.', 'Coleta de dados, organização e registro; Construção de diferentes tipos de gráficos para representá-los e interpretação das informações', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 6, 'EF06MA34', 'Interpretar e desenvolver fluxogramas simples, identificando as relações entre os objetos representados (por exemplo, posição de cidades considerando as estradas que as unem, hierarquia dos funcionários de uma empresa etc.).', 'Diferentes tipos de representação de informações: gráficos e fluxogramas', 0);
--INSERTS DO ANO 7
--Habilidades NÚMEROS do 7º ano: MA01 - MA12
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA01', 'Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo, podendo incluir máximo divisor comum ou mínimo múltiplo comum, por meio de estratégias diversas, sem a aplicação de algoritmos.', 'Múltiplos e divisores de um número natural', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA02', 'Resolver e elaborar problemas que envolvam porcentagens, como os que lidam com acréscimos e decréscimos simples, utilizando estratégias pessoais, cálculo mental e calculadora, no contexto de educação financeira, entre outros.', 'Cálculo de porcentagens e de acréscimos e decréscimos simples', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA03', 'Comparar e ordenar números inteiros em diferentes contextos, incluindo o histórico, associá-los a pontos da reta numérica e utilizá-los em situações que envolvam adição e subtração.', 'Números inteiros: usos, história, ordenação, associação com pontos da reta numérica e operações', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA04', 'Resolver e elaborar problemas que envolvam operações com números inteiros.', 'Números inteiros: usos, história, ordenação, associação com pontos da reta numérica e operações', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA05', 'Resolver um mesmo problema utilizando diferentes algoritmos.', 'Fração e seus significados: como parte de inteiros, resultado da divisão, razão e operador', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA06', 'Reconhecer que as resoluções de um grupo de problemas que têm a mesma estrutura podem ser obtidas utilizando os mesmos procedimentos.', 'Fração e seus significados: como parte de inteiros, resultado da divisão, razão e operador', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA07', 'Representar por meio de um fluxograma os passos utilizados para resolver um grupo de problemas.', 'Fração e seus significados: como parte de inteiros, resultado da divisão, razão e operador', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA08', 'Comparar e ordenar frações associadas às ideias de partes de inteiros, resultado da divisão, razão e operador.', 'Fração e seus significados: como parte de inteiros, resultado da divisão, razão e operador', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA09', 'Utilizar, na resolução de problemas, a associação entre razão e fração, como a fração 2/3 para expressar a razão de duas partes de uma grandeza para três partes da mesma ou três partes de outra grandeza.', 'Fração e seus significados: como parte de inteiros, resultado da divisão, razão e operador', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA10', 'Comparar e ordenar números racionais em diferentes contextos e associá-los a pontos da reta numérica.', 'Números racionais na representação fracionária e na decimal: usos, ordenação e associação com pontos da reta numérica e operações', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA11', 'Compreender e utilizar a multiplicação e a divisão de números racionais, a relação entre elas e suas propriedades operatórias.', 'Números racionais na representação fracionária e na decimal: usos, ordenação e associação com pontos da reta numérica e operações', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 7, 'EF07MA12', 'Resolver e elaborar problemas que envolvam as operações com números racionais.', 'Números racionais na representação fracionária e na decimal: usos, ordenação e associação com pontos da reta numérica e operações', 3);
--Habilidades ÁLGEBRA do 7º ano: MA13 - MA18
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA13', 'Compreender a ideia de variável, representada por letra ou símbolo, para expressar relação entre duas grandezas, diferenciando-a da ideia de incógnita.', 'Linguagem algébrica: variável e incógnita', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA14', 'Classificar sequências em recursivas e não recursivas, reconhecendo que o conceito de recursão está presente não apenas na matemática, mas também nas artes e na literatura.', 'Linguagem algébrica: variável e incógnita', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA15', 'Utilizar a simbologia algébrica para expressar regularidades encontradas em sequências numéricas.', 'Linguagem algébrica: variável e incógnita', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA16', 'Reconhecer se duas expressões algébricas obtidas para descrever a regularidade de uma mesma sequência numérica são ou não equivalentes.', 'Equivalência de expressões algébricas: identificação da regularidade de uma sequência numérica', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA17', 'Resolver e elaborar problemas que envolvam variação de proporcionalidade direta e de proporcionalidade inversa entre duas grandezas, utilizando sentença algébrica para expressar a relação entre elas.', 'Problemas envolvendo grandezas diretamente proporcionais e grandezas inversamente proporcionais', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 7, 'EF07MA18', 'Resolver e elaborar problemas que possam ser representados por equações polinomiais de 1º grau, redutíveis à forma ax + b = c, fazendo uso das propriedades da igualdade.', ' Equações polinomiais do 1º grau', 4);
--Habilidades GEOMETRIA do 7º ano: MA19 - MA28
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA19', 'Realizar transformações de polígonos representados no plano cartesiano, decorrentes da multiplicação das coordenadas de seus vértices por um número inteiro.', 'Transformações geométricas de polígonos no plano cartesiano: multiplicação das coordenadas por um número inteiro e obtenção de simétricos em relação aos eixos e à origem', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA20', 'Reconhecer e representar, no plano cartesiano, o simétrico de figuras em relação aos eixos e à origem.', 'Transformações geométricas de polígonos no plano cartesiano: multiplicação das coordenadas por um número inteiro e obtenção de simétricos em relação aos eixos e à origem', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA21', 'Reconhecer e construir figuras obtidas por simetrias de translação, rotação e reflexão, usando instrumentos de desenho ou softwares de geometria dinâmica e vincular esse studo a representações planas de obras de arte, elementos arquitetônicos, entre outros.', 'Simetrias de translação, rotação e reflexão', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA22', 'Construir circunferências, utilizando compasso, reconhecê-las como lugar geométrico e utilizá-las para fazer composições artísticas e resolver problemas que envolvam objetos equidistantes.', 'A circunferência como lugar geométrico', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA23', 'Verificar relações entre os ângulos formados por retas paralelas cortadas por uma transversal, com e sem uso de softwares de geometria dinâmica.', 'Relações entre os ângulos formados por retas paralelas intersectadas por uma transversal', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA24', 'Construir triângulos, usando régua e compasso, reconhecer a condição de existência do triângulo quanto à medida dos lados e verificar que a soma das medidas dos ângulos internos de um triângulo é 180°.', 'Triângulos: construção, condição de existência e soma das medidas dos ângulos internos', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA25', 'Reconhecer a rigidez geométrica dos triângulos e suas aplicações, como na construção de estruturas arquitetônicas (telhados, estruturas metálicas e outras) ou nas artes plásticas.', 'Triângulos: construção, condição de existência e soma das medidas dos ângulos internos', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA26', 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um triângulo qualquer, conhecidas as medidas dos três lados.', 'Triângulos: construção, condição de existência e soma das medidas dos ângulos internos', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA27', 'Calcular medidas de ângulos internos de polígonos regulares, sem o uso de fórmulas, e estabelecer relações entre ângulos internos e externos de polígonos, preferencialmente vinculadas à construção de mosaicos e de ladrilhamentos.', 'Polígonos regulares: quadrado e triângulo equilátero', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 7, 'EF07MA28', 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular (como quadrado e triângulo equilátero), conhecida a medida de seu lado.', 'Polígonos regulares: quadrado e triângulo equilátero', 0);
--Habilidades GRANDEZAS E MEDIDAS do 7º ano: MA29 - MA33
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 7, 'EF07MA29', 'Resolver e elaborar problemas que envolvam medidas de grandezas inseridos em contextos oriundos de situações cotidianas ou de outras áreas do conhecimento, reconhecendo que toda medida empírica é aproximada.', 'Problemas envolvendo medições', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 7, 'EF07MA30', 'Resolver e elaborar problemas de cálculo de medida do volume de blocos retangulares, envolvendo as unidades usuais (metro cúbico, decímetro cúbico e centímetro cúbico).', 'Cálculo de volume de blocos retangulares, utilizando unidades de medida convencionais mais usuais', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 7, 'EF07MA31', 'Estabelecer expressões de cálculo de área de triângulos e de quadriláteros.', 'Equivalência de área de figuras planas: cálculo de áreas de figuras que podem ser decompostas por outras, cujas áreas podem ser facilmente determinadas como triângulos e quadriláteros', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 7, 'EF07MA32', 'Resolver e elaborar problemas de cálculo de medida de área de figuras planas que podem ser decompostas por quadrados, retângulos e/ou triângulos, utilizando a equivalência entre áreas. ', 'Equivalência de área de figuras planas: cálculo de áreas de figuras que podem ser decompostas por outras, cujas áreas podem ser facilmente determinadas como triângulos e quadriláteros', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 7, 'EF07MA33', 'Estabelecer o número  como a razão entre a medida de uma circunferência e seu diâmetro, para compreender e resolver problemas, inclusive os de natureza histórica.', 'Medida do comprimento da circunferência', 0);
--Habilidades PROBABILIDADE E ESTATÍSTICA do 7º ano: MA34 - MA37
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 7, 'EF07MA34', 'Planejar e realizar experimentos aleatórios ou simulações que envolvem cálculo de probabilidades ou estimativas por meio de frequência de ocorrências. ', 'Experimentos aleatórios: espaço amostral e estimativa de probabilidade por meio de frequência de ocorrências', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 7, 'EF07MA35', 'Compreender, em contextos significativos, o significado de média estatística como indicador da tendência de uma pesquisa, calcular seu valor e relacioná-lo, intuitivamente, com a amplitude do conjunto de dados.', 'Estatística: média e amplitude de um conjunto de dados', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 7, 'EF07MA36', 'Planejar e realizar pesquisa envolvendo tema da realidade social, identificando a necessidade de ser censitária ou de usar amostra, e interpretar os dados para comunicá-los por meio de relatório escrito, tabelas e gráficos, com o apoio de planilhas eletrônicas.', 'Pesquisa amostral e pesquisa censitária; Planejamento de pesquisa, coleta e organização dos dados, construção de tabelas e gráficos e interpretação das informações', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 7, 'EF07MA37', 'Interpretar e analisar dados apresentados em gráfico de setores divulgados pela mídia e compreender quando é possível ou conveniente sua utilização.', 'Gráficos de setores: interpretação, pertinência e construção para representar conjunto de dados', 0);
--INSERTS DO ANO 8
--Habilidades NÚMEROS do 8º ano: MA01 - MA05
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 8, 'EF08MA01', 'Efetuar cálculos com potências de expoentes inteiros e aplicar esse conhecimento na representação de números em notação científica.', 'Notação científica', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 8, 'EF08MA02', 'Resolver e elaborar problemas usando a relação entre potenciação e radiciação, para representar uma raiz como potência de expoente fracionário.', 'Potenciação e radiciação', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 8, 'EF08MA03', 'Resolver e elaborar problemas de contagem cuja resolução envolva a aplicação do princípio multiplicativo.', 'O princípio multiplicativo da contagem', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 8, 'EF08MA04', 'Resolver e elaborar problemas, envolvendo cálculo de porcentagens, incluindo o uso de tecnologias digitais.', 'Porcentagens', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 8, 'EF08MA05', 'Reconhecer e utilizar procedimentos para a obtenção de uma fração geratriz para uma dízima periódica.', 'Dízimas periódicas: fração geratriz', 0);
--Habilidades ÁLGEBRA do 8º ano: MA06 - MA13
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA06', 'Resolver e elaborar problemas que envolvam cálculo do valor numérico de expressões algébricas, utilizando as propriedades das operações.', 'Valor numérico de expressões algébricas', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA07', 'Associar uma equação linear de 1º grau com duas incógnitas a uma reta no plano cartesiano.', 'Associação de uma equação linear de 1º grau a uma reta no plano cartesiano', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA08', 'Resolver e elaborar problemas relacionados ao seu contexto próximo, que possam ser representados por sistemas de equações de 1º grau com duas incógnitas e interpretá-los, utilizando, inclusive, o plano cartesiano como recurso.', 'Sistema de equações polinomiais de 1º grau: resolução algébrica e representação no plano cartesiano', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA09', 'Resolver e elaborar, com e sem uso de tecnologias, problemas que possam ser representados por equações polinomiais de 2º grau do tipo ax2 = b.', 'Equação polinomial de 2º grau do tipo ax2 = b', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA10', 'Identificar a regularidade de uma sequência numérica ou figural não recursiva e construir um algoritmo por meio de um fluxograma que permita indicar os números ou as figuras seguintes.', 'Sequências recursivas e não recursivas', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA11', 'Identificar a regularidade de uma sequência numérica recursiva e construir um algoritmo por meio de um fluxograma que permita indicar os números seguintes.', 'Sequências recursivas e não recursivas', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA12', 'Identificar a natureza da variação de duas grandezas, diretamente, inversamente proporcionais ou não proporcionais, expressando a relação existente por meio de sentença algébrica e representá-la no plano cartesiano.', 'Variação de grandezas: diretamente proporcionais, inversamente proporcionais ou não proporcionais', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 8, 'EF08MA13', 'Resolver e elaborar problemas que envolvam grandezas diretamente ou inversamente proporcionais, por meio de estratégias variadas.', 'Variação de grandezas: diretamente proporcionais, inversamente proporcionais ou não proporcionais', 2);
--Habilidades GEOMETRIA do 8º ano: MA14 - MA18
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 8, 'EF08MA14', 'Demonstrar propriedades de quadriláteros por meio da identificação da congruência de triângulos.', 'Congruência de triângulos e demonstrações de propriedades de quadriláteros', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 8, 'EF08MA15', 'Construir, utilizando instrumentos de desenho ou softwares de geometria dinâmica, mediatriz, bissetriz, ângulos de 90°, 60°, 45° e 30° e polígonos regulares.', 'Construções geométricas: ângulos de 90°, 60°, 45° e 30° e polígonos regulares', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 8, 'EF08MA16', 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um hexágono regular de qualquer área, a partir da medida do ângulo central e da utilização de esquadros e compasso.', 'Construções geométricas: ângulos de 90°, 60°, 45° e 30° e polígonos regulares', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 8, 'EF08MA17', 'Aplicar os conceitos de mediatriz e bissetriz como lugares geométricos na resolução de problemas.', 'Mediatriz e bissetriz como lugares geométricos: construção e problemas', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 8, 'EF08MA18', 'Reconhecer e construir figuras obtidas por composições de transformações geométricas (translação, reflexão e rotação), com o uso de instrumentos de desenho ou de softwares de geometria dinâmica.', 'Transformações geométricas: simetrias de translação, reflexão e rotação', 0);
--Habilidades MEDIDAS E GRANDEZAS do 8º ano: MA19 - MA21
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 8, 'EF08MA19', 'Resolver e elaborar problemas que envolvam medidas de área de figuras geométricas, utilizando expressões de cálculo de área (quadriláteros, triângulos e círculos), em situações como determinar medida de terrenos. ', 'Área de figuras planas; Área do círculo e comprimento de sua circunferência', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 8, 'EF08MA20', 'Reconhecer a relação entre um litro e um decímetro cúbico e a relação entre litro e metro cúbico, para resolver problemas de cálculo de capacidade de recipientes.', 'Volume de bloco retangular; Medidas de capacidade', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 8, 'EF08MA21', 'Resolver e elaborar problemas que envolvam o cálculo do volume de recipiente cujo formato é o de um bloco retangular.', 'Volume de bloco retangular; Medidas de capacidade', 4);
--Habilidades PROBABILIDADE E ESTATÍSTICA do 8º ano: MA22 - MA27
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA22', 'Calcular a probabilidade de eventos, com base na construção do espaço amostral, utilizando o princípio multiplicativo, e reconhecer que a soma das probabilidades de todos os elementos do espaço amostral é igual a 1.', 'Princípio multiplicativo da contagem; Soma das probabilidades de todos os elementos de um espaço amostral', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA23', 'Avaliar a adequação de diferentes tipos de gráficos para representar um conjunto de dados de uma pesquisa. ', 'Gráficos de barras, colunas, linhas ou setores e seus elementos constitutivos e adequação para determinado conjunto de dados', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA24', 'Classificar as frequências de uma variável contínua de uma pesquisa em classes, de modo que resumam os dados de maneira adequada para a tomada de decisões.', 'Organização dos dados de uma variável contínua em classes', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA25', 'Obter os valores de medidas de tendência central de uma pesquisa estatística (média, moda e mediana) com a compreensão de seus significados e relacioná-los com a dispersão de dados, indicada pela amplitude. ', 'Medidas de tendência central e de dispersão', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA26', 'Selecionar razões, de diferentes naturezas (física, ética ou econômica), que justificam a realização de pesquisas amostrais e não censitárias, e reconhecer que a seleção da amostra pode ser feita de diferentes maneiras (amostra casual simples, sistemática e estratificada).', 'Pesquisas censitária ou amostral; Planejamento e execução de pesquisa amostral', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 8, 'EF08MA27', 'Planejar e executar pesquisa amostral, selecionando uma técnica de amostragem adequada, e escrever relatório que contenha os gráficos apropriados para representar os conjuntos de dados, destacando aspectos como as medidas de tendência central, a amplitude e as conclusões.', 'Pesquisas censitária ou amostral; Planejamento e execução de pesquisa amostral', 0);
--INSERTS DO ANO 9
--Habilidades NÚMEROS do 9º ano: MA01 - MA05
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 9, 'EF09MA01', 'Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional (como as medidas de diagonais de um polígono e alturas de um triângulo, quando se toma a medida de cada lado como unidade).', 'Necessidade dos números reais para medir qualquer segmento de reta; Números irracionais: reconhecimento e localização de alguns na reta numérica', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 9, 'EF09MA02', 'Reconhecer um número irracional como um número real cuja representação decimal é infinita e não periódica, e estimar a localização de alguns deles na reta numérica.', 'Necessidade dos números reais para medir qualquer segmento de reta; Números irracionais: reconhecimento e localização de alguns na reta numérica', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 9, 'EF09MA03', 'Efetuar cálculos com números reais, inclusive potências com expoentes fracionários.', 'Potências com expoentes negativos e fracionários', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 9, 'EF09MA04', 'Resolver e elaborar problemas com números reais, inclusive em notação científica, envolvendo diferentes operações.', 'Números reais: notação científica e problemas', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (1, 9, 'EF09MA05', 'Resolver e elaborar problemas que envolvam porcentagens, com a ideia de aplicação de percentuais sucessivos e a determinação das taxas percentuais, preferencialmente com o uso de tecnologias digitais, no contexto da educação financeira.', 'Porcentagens: problemas que envolvem cálculo de percentuais sucessivos', 4);
--Habilidades ÁLGEBRA do 9º ano: MA06 - MA09
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 9, 'EF09MA06', 'Compreender as funções como relações de dependência unívoca entre duas variáveis e suas representações numérica, algébrica e gráfica e utilizar esse conceito para analisar situações que envolvam relações funcionais entre duas variáveis.', 'Funções: representações numérica, algébrica e gráfica', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 9, 'EF09MA07', 'Resolver problemas que envolvam a razão entre duas grandezas de espécies diferentes, como velocidade e densidade demográfica.', 'Razão entre grandezas de espécies diferentes', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 9, 'EF09MA08', 'Resolver e elaborar problemas que envolvam relações de proporcionalidade direta e inversa entre duas ou mais grandezas, inclusive escalas, divisão em partes proporcionais e taxa de variação, em contextos socioculturais, ambientais e de outras áreas.', 'Grandezas diretamente proporcionais e grandezas inversamente proporcionais', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (2, 9, 'EF09MA09', 'Compreender os processos de fatoração de expressões algébricas, com base em suas relações com os produtos notáveis, para resolver e elaborar problemas que possam ser representados por equações polinomiais do 2º grau.', 'Expressões algébricas: fatoração e produtos notáveis; Resolução de equações polinomiais do 2º grau por meio de fatorações', 2);
--Habilidades GEOMETRIA do 9º ano: MA10 - MA17
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA10', 'Demonstrar relações simples entre os ângulos formados por retas paralelas cortadas por uma transversal.', 'Demonstrações de relações entre os ângulos formados por retas paralelas intersectadas por uma transversal', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA11', 'Resolver problemas por meio do estabelecimento de relações entre arcos, ângulos centrais e ângulos inscritos na circunferência, fazendo uso, inclusive, de softwares de geometria dinâmica.', 'Relações entre arcos e ângulos na circunferência de um círculo', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA12', 'Reconhecer as condições necessárias e suficientes para que dois triângulos sejam semelhantes.', 'Semelhança de triângulos', 1);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA13', 'Demonstrar relações métricas do triângulo retângulo, entre elas o teorema de Pitágoras, utilizando, inclusive, a semelhança de triângulos.', 'Relações métricas no triângulo retângulo; Teorema de Pitágoras: verificações experimentais e demonstração; Retas paralelas cortadas por transversais: teoremas de proporcionalidade e verificações experimentais', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA14', 'Resolver e elaborar problemas de aplicação do teorema de Pitágoras ou das relações de proporcionalidade envolvendo retas paralelas cortadas por secantes.', 'Relações métricas no triângulo retângulo; Teorema de Pitágoras: verificações experimentais e demonstração; Retas paralelas cortadas por transversais: teoremas de proporcionalidade e verificações experimentais', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA15', 'Descrever, por escrito e por meio de um fluxograma, um algoritmo para a construção de um polígono regular cuja medida do lado é conhecida, utilizando régua e compasso, como também softwares.', 'Polígonos regulares', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA16', 'Determinar o ponto médio de um segmento de reta e a distância entre dois pontos quaisquer, dadas as coordenadas desses pontos no plano cartesiano, sem o uso de fórmulas, e utilizar esse conhecimento para calcular, por exemplo, medidas de perímetros e áreas de figuras planas construídas no plano.', 'Distância entre pontos no plano cartesiano', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (3, 9, 'EF09MA17', 'Reconhecer vistas ortogonais de figuras espaciais e aplicar esse conhecimento para desenhar objetos em perspectiva.', 'Vistas ortogonais de figuras espaciais', 0);
--Habilidades GRANDEZAS E MEDIDAS do 9º ano: MA18 - MA19
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 9, 'EF09MA18', 'Reconhecer e empregar unidades usadas para expressar medidas muito grandes ou muito pequenas, tais como distância entre planetas e sistemas solares, tamanho de vírus ou de células, capacidade de armazenamento de computadores, entre outros.', 'Unidades de medida para medir distâncias muito grandes e muito pequenas; Unidades de medida utilizadas na informática', 2);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (4, 9, 'EF09MA19', 'Resolver e elaborar problemas que envolvam medidas de volumes de prismas e de cilindros retos, inclusive com uso de expressões de cálculo, em situações cotidianas.', 'Volume de prismas e cilindros', 4);
--Habilidades GRANDEZAS E MEDIDAS do 9º ano: MA20 - MA23
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 9, 'EF09MA20', 'Reconhecer, em experimentos aleatórios, eventos independentes e dependentes e calcular a probabilidade de sua ocorrência, nos dois casos.', 'Análise de probabilidade de eventos aleatórios: eventos dependentes e independentes', 4);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 9, 'EF09MA21', 'Analisar e identificar, em gráficos divulgados pela mídia, os elementos que podem induzir, às vezes propositadamente, erros de leitura, como escalas inapropriadas, legendas não explicitadas corretamente, omissão de informações importantes (fontes e datas), entre outros. ', 'Análise de gráficos divulgados pela mídia: elementos que podem induzir a erros de leitura ou de interpretação', 0);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 9, 'EF09MA22', 'Escolher e construir o gráfico mais adequado (colunas, setores, linhas), com ou sem uso de planilhas eletrônicas, para apresentar um determinado conjunto de dados, destacando aspectos como as medidas de tendência central.', 'Leitura, interpretação e representação de dados de pesquisa expressos em tabelas de dupla entrada, gráficos de colunas simples e agrupadas, gráficos de barras e de setores e gráficos pictóricos', 3);
INSERT INTO tb_habilidades (id_unidade, ano_Escolar, sigla, descricao, objeto_Conhecimento, bimestre) VALUES (5, 9, 'EF09MA23', 'Planejar e executar pesquisa amostral envolvendo tema da realidade social e comunicar os resultados por meio de relatório contendo avaliação de medidas de tendência central e da amplitude, tabelas e gráficos adequados, construídos com o apoio de planilhas eletrônicas.', 'Planejamento e execução de pesquisa amostral e apresentação de relatório', 3);

--INSERTS TABELA tb_turma
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (6, 11, 'TURMA6A');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (6, 12, 'TURMA6B');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (6, 13, 'TURMA6C');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (7, 14, 'TURMA7A');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (7, 15, 'TURMA7B');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (7, 11, 'TURMA7C');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (8, 13, 'TURMA8A');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (8, 14, 'TURMA8B');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (9, 12, 'TURMA9A');
INSERT INTO tb_turma (ano_escolar, id_professor, codigo) VALUES (9, 15, 'TURMA9B');

--INSERTS TABELA tb_aluno_turma
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (1, 1); --aluno Lara, TURMA6A
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (2, 1); --aluno Enzo, TURMA6A
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (3, 2); --aluno Enzo, TURMA6B
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (4, 2); --aluno Enzo, TURMA6B
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (5, 3); --aluno Enzo, TURMA6C
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (6, 3); --aluno Enzo, TURMA6C
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (7, 4); --aluno Enzo, TURMA7A
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (8, 5); --aluno Enzo, TURMA7B
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (9, 8); --aluno Enzo, TURMA8B
INSERT INTO tb_aluno_turma (id_aluno, id_turma) VALUES (10, 9); --aluno Enzo, TURMA9A

--INSERTS DA TABELA tb_questao
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (1, '50', '500', '5', '5000', '0.5', 'Qual o valor posicional do dígito 5 no número 3.582?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (1, '150', '125', '130', '145', '160', 'Resolva: 75 + 128 - 53 = ?', 'D');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (1, '36', '42', '40', '32', '48', 'Qual o resultado de 6 × 7?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (1, '3/6', '5/6', '1', '2/3', '1/6', 'Quanto é 2/3 + 1/6?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (1, '0.25', '0.5', '0.75', '1.0', '1.25', 'Qual o número decimal equivalente a 3/4?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (2, '6', '9', '7', '8', '5', 'Resolva: √49 = ?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (2, '25', '52', '13', '16', '18', 'Quanto é 3² + 4²?', 'E');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (2, 'R$160,00', 'R$150,00', 'R$170,00', 'R$180,00', 'R$200,00', 'Maria comprou um produto com 20% de desconto. Se o preço original era R$ 200,00, qual foi o valor pago?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (2, '4', '3', '2', '1', '5', 'Qual a razão entre 12 e 3?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (3, '10', '20', '30', '40', '50', 'Resolva a expressão: (2 + 3) × 4', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (3, 'R$20,00', 'R$25,00', 'R$15,00', 'R$30,00', 'R$10,00', 'Um produto que custava R$ 25,00 teve um desconto de R$ 5,00. Qual o novo valor?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (3, '40', '45', '50', '35', '55', 'Qual é a média aritmética de 30, 40 e 50?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (3, 'R$200,00', 'R$180,00', 'R$220,00', 'R$160,00', 'R$240,00', 'Um trabalhador recebe R$ 20 por hora. Quanto ele ganha em 8 horas?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (3, '5', '4', '3', '2', '1', 'Quantos vértices tem um triângulo?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (4, 'Área', 'Volume', 'Perímetro', 'Altura', 'Diâmetro', 'O que representa o valor ao redor de uma figura geométrica?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (4, 'Círculo', 'Retângulo', 'Triângulo', 'Quadrado', 'Trapézio', 'Qual figura possui todos os lados e ângulos iguais?', 'D');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (4, '90°', '180°', '270°', '360°', '45°', 'Qual é a soma dos ângulos internos de um triângulo?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (4, '3', '4', '5', '6', '8', 'Quantos lados tem um pentágono?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (4, 'Volume', 'Altura', 'Área', 'Perímetro', 'Raio', 'A medida da superfície de um objeto plano é chamada de:', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (5, 'Quilômetro', 'Metro', 'Centímetro', 'Milímetro', 'Litro', 'Qual dessas unidades mede comprimento?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (5, '1000 mL', '100 mL', '10 mL', '1 mL', '500 mL', 'Quantos mililitros há em 1 litro?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (5, '1 hora', '60 segundos', '3600 segundos', '30 minutos', '120 segundos', 'Quantos segundos há em uma hora?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (5, 'Peso', 'Tempo', 'Volume', 'Temperatura', 'Comprimento', 'O que um termômetro mede?', 'D');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (5, '0,5 kg', '500 g', '5 kg', '0,05 kg', '50 g', 'Qual é o equivalente de 500 gramas em quilogramas?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (6, 'Moda', 'Mediana', 'Média', 'Desvio padrão', 'Variância', 'Qual é o valor que mais se repete em um conjunto de dados?', 'A');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (6, '8', '10', '12', '14', '16', 'Dado o conjunto: 2, 4, 6, 8, 10, 12, qual é a mediana?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (6, '10', '12', '14', '16', '18', 'Se a média de três números é 14, qual é a soma desses números?', 'C');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (6, '1', '2', '3', '4', '5', 'Quantos gráficos de barras simples são necessários para mostrar dois conjuntos de dados?', 'B');
INSERT INTO tb_questao (id_habilidade, alternativa_a, alternativa_b, alternativa_c, alternativa_d, alternativa_e, enunciado, resposta_correta) VALUES (6, 'Sim', 'Não', 'Às vezes', 'Nunca', 'Talvez', 'Um gráfico de setores é adequado para representar partes de um todo?', 'A');

